### ISSUE TITLE
the same here just try to search how to implmement that with python 

### ISSUE THREAD

**Issue by moatasemelsayed** [MennaAbdelatif/Python#2]
https://github.com/MennaAbdelatif/Python/blob/92e4cca52f947fa9172d778c003e03219a4c17c1/Searching_of_Num.py#L1

**Comment by MennaAbdelatif** [comment]
@moatasemelsayed I update it #2

**Comment by moatasemelsayed** [comment]
this one still not updated

**Comment by MennaAbdelatif** [comment]
@moatasemelsayed fixed #2

**Comment by moatasemelsayed** [comment]
List by default has member for count could you check that

**Comment by MennaAbdelatif** [comment]
Okay i got it update it with count() method
