### ISSUE TITLE
replace it with list and in 

### ISSUE THREAD

**Issue by moatasemelsayed** [MennaAbdelatif/Python#3]
https://github.com/MennaAbdelatif/Python/blob/92e4cca52f947fa9172d778c003e03219a4c17c1/vowels_consonant.py#L2

**Comment by MennaAbdelatif** [comment]
fixed #3

**Comment by MennaAbdelatif** [comment]
@moatasemelsayed  fixed #3

**Comment by moatasemelsayed** [comment]
good
